### PR TITLE
adding crud views for user table #20

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
for some reason when Brad pulls he is not shown all of the folders that I've made.  Though they are empty folders.

**Comment by clburns107** [comment]
Brad is unable to get any pages to show up after racking up. We know these pages showed when i racked up.

**Comment by clburns107** [comment]
Cant connect to database with postico :( Using db name project-db-name from config/database.yml file

**Comment by sumeetjain** [comment]
On my way!

**Comment by clburns107** [comment]
ok so my postico works fine now but Brads is still not displaying the tables

**Comment by clburns107** [comment]
we are at a point where we cant test our submit form for updating a user page because we need a session id.  We cant make a session id because we need a login form. we cant make a login form because we havent completed and merged our submit form for updating a user. HELP!

**Comment by halfghaninne** [comment]
Can you artificially set a session id for the time-being, in order to test?

**Comment by sumeetjain** [comment]
Or any other fake-it solution. Whatever solution you choose, make an Issue™ for un-faking it that you get to _after_ this feature is done.

**Comment by halfghaninne** [comment]
:+1:

**Comment by halfghaninne** [comment]
:+1:

**Pull request merged**
