### PR TITLE
crud ratings #21

### PR DESCRIPTION
**Pull request by bbiehl**

### CODE REVIEW

**Comment by clburns107** [comment]
Help! we're trying to get ratings to save with attributes in a url but we're having issues

**Comment by clburns107** [comment]
we're getting a no data error and cant figure out why

**Comment by halfghaninne** [comment]
Can you give me some more information? What were you trying to do? What was the exact error. Was their a line reference in the error?

**Comment by clburns107** [comment]
When redirecting to the Review Movie page and using the @movie.id variable in the redirect request the page displays a no method found error for @movie.title because movie is nil.   So we put erb tags around @movie.id variable.  Now page displays no data error with a sad face.

**Comment by clburns107** [comment]
i need to talk out how to make a collection of multiple collections, of multiple collections... :)

**Comment by sumeetjain** [comment]
Please provide more information. What specific part of this feature are you trying to build? What does the flow from one page to another page for this feature look like? What kind of conversation have you and Brad had about this?

Alex and I are about to have a staff meeting, so in the meantime consider using another group as your rubber duck.

**Comment by clburns107** [comment]
we're having trouble displaying all ratings for our friends for one movie.  receiving user_id of 0 and have no clue where that is coming from.

**Pull request merged**
