### PR TITLE
update-ratings #50

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by bbiehl** [comment]
Implementing Rating.exist? Boolean method to check if a users rating for a movie already exists.

This might conflict with ratings already in our heroku database, since I have rated Top Gun 5 stars several times on our live site.

**Comment by bbiehl** [comment]
Updated controller action does not conflict with multiple ratings for the same movie, if just updates the first ratings object in the ratings database.

**Comment by bbiehl** [comment]
And now, a user is not able to enter multiple ratings for the same movie.

**Comment by halfghaninne** [comment]
:+1:

**Pull request merged**
